name: 'Send Workchat Notification'
author: rodrigo-nogues
inputs:
  api-endpoint:
    description: 'Workplace Publisher API endpoint.'
    required: true
  api-key:
    description: 'Workplace Publisher API key.'
    required: true
  recipients-id:
    description: 'Workplace ID of the message recipients separated by spaces (add "t_" for groups and make sure bot is a member of the group).'
    required: true
  text:
    description: 'Message text.'
    required: true
  button-text:
    description: 'Text of the action button.'
    default: 'View'
  button-url:
    description: 'URL of the action button.'
    required: true
runs:
  using: "composite"
  steps:
    - run: >-
        python3 ./.github/actions/wp-publisher/wp-notify.py
          "${{ inputs.api-endpoint }}"
          "${{ inputs.api-key }}"
          "${{ inputs.text }}"
          "${{ inputs.button-url }}"
          "${{ inputs.button-text }}"
          ${{ inputs.recipients-id }}
      shell: bash
